### ISSUE TITLE
[Bug]: pkmer插件市场的brat版本是两年前的

### ISSUE THREAD

**Issue by aiyou9** [PKM-er/Pkmer-Obsidian#17]
### Bug Description

![image](https://github.com/PKM-er/Pkmer-Obsidian/assets/15712822/3736370f-29af-4f3a-9c6e-dd9fdad82f7e)

### Obsidian Version

1.5.3

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by cumany** [comment]
已反馈 修复
